ALTER TABLE users
ADD COLUMN IF NOT EXISTS is_active BOOLEAN DEFAULT TRUE;

ALTER TABLE users
ADD COLUMN IF NOT EXISTS role VARCHAR(50) DEFAULT 'User';

ALTER TABLE users
ADD COLUMN last_logged_in TIMESTAMPTZ;

ALTER TABLE users
ADD COLUMN created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP;